### ISSUE TITLE
Grand Theft Auto (PAL)

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/PSX_MiSTer#120]
**Issue:**
Engine noises, tire squeals are completely off. All you can hear is a strange ticking sound.

https://youtu.be/afmMWzCIhks

**Reproduce:**
Get in the car and go for a ride :)

**Workaround:**
none

**BIOS:**
7502

**CD Image:**
Redump bin/cue

**Core Version:**
PSX_DualSDRAM20220526

**Comment by davedoc1984** [comment]
Can confirm this also happens with Euro Demo 28 - Grand Theft Auto Demo. Identical issue to the one Kuba is reporting here.

**Comment by fjmartinez2k** [comment]
Workaround: play USA version, no audio glitches.

PAL's audio is still broken

**Comment by RobertPeip** [comment]
Seems related to DMA/SPU transfer speed. SPU RAM is wrong when the bug occurs.

**Comment by Kuba-J** [comment]
fixed - core 20220730

**Comment by davedoc1984** [comment]
Euro Demo 28 GTA Demo is still broken, not the same as before but the Audio (Engine Noise) is flipping on and off.

**Comment by Kuba-J** [comment]
Fixed
